portlet
pulse-us/portlet pull request #1
Opened 2018-02-16 17:47 UTC by brianlindsy

2018-02-16 18:00 UTC, andlar requested changes
Can you also add the checkstyle.xml from the other PULSE projects too?

2018-02-16 18:00 UTC, andlar commented on src/main/resources/content/Language.properties
> +action.NEW_PERMISSION_FOR_SAMPLE=Caliphr Permission 1
Probably should have a different permission

2018-02-16 19:48 UTC, andlar approved these changes

2018-02-16 19:58 UTC, andlar commented
Oh, is there a README? If not, can you put in a basic one with steps on build / deploy?

2018-02-16 20:52 UTC, andlar approved these changes

2018-02-19 14:41 UTC, ssavarala approved these changes

2018-02-20 15:27 UTC, sriniadhiwork approved these changes
small suggestion: GrantedPermissionModel extends GrantedAuthority, maybe we can annotate getAuthority with @Override for clarity. also the Boolean value is used for revokes I believe, perhaps naming as Boolean granted?

2018-02-22 18:11 UTC, merged